import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {

  const countdownDate = new Date('August 26, 2022 00:00:00');
  // const [countdownDate, setCountdown] = useEffect(eventDate);
  const today = new Date();

  const zeroPad = (num, places) => String(num).padStart(places, '0')

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          1st Internation Symposium on Blockchain Advancements (ISBA 2022)
        </h1>

        <p className={styles.description}>
          Lorem Ipsum Dolor Sit Amet{' '}
        </p>

        <div className={styles.countdown}>
          <div className={[styles.countdownElement]}>
            <p>{(zeroPad(Math.abs(countdownDate.getMonth()-today.getMonth()),2)).toString()}</p>
            <p> Months</p>
          </div>
          <p className = "text-white font-bold p-2 m-1">:</p>
          <div className={[styles.countdownElement]}>
            <p>{(zeroPad(Math.abs(countdownDate.getDate()-today.getDate()),2)).toString()}</p>
            <p> Days</p>
          </div>
          <p className = "text-white font-bold p-2 m-1">:</p>
          <div className={[styles.countdownElement]}>
            <p>{(zeroPad(Math.abs(countdownDate.getHours()-today.getHours()),2)%24).toString()}</p>
            <p> Hours</p>
          </div>
          <p className = "text-white font-bold p-2 m-1">:</p>
          <div className={[styles.countdownElement]}>
            <p>{(zeroPad(Math.abs(countdownDate.getMinutes()-today.getMinutes()%60),2)).toString()}</p>
            <p> Minutes</p>
          </div>
          <div className={[styles.countdownElement]}>
            <p>{(zeroPad(Math.abs(countdownDate.getSeconds()-today.getSeconds()),2)).toString()}</p>
            <p> Seconds</p>
          </div>
        </div>

        <button className={styles.button}>Register for the event</button>

        <div className={styles.grid}>

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
